#!/usr/bin/python3

import random
import time


def generate_expression():
    x = random.randint(1, 9)
    operators = ['+', '-', '*', '/']
    operator = random.choice(operators)
    y = random.randint(1, 9)
    return f"{x} {operator} {y}"


N = random.randint(120, 180)
for _ in range(N):
    expression = generate_expression()
    print(expression, flush=True)
    time.sleep(1)
